### ISSUE TITLE
Misleading error after upgrading from 2.3.2 to 3.0.0 - "Tried to register two views with the same name RNCSafeAreaProvider"

### ISSUE THREAD

**Issue by pospieszynski** [react-native-elements/react-native-elements#2721]
**Explain what you did (Required)**

I work on upgrading _react-native-elements_ from 2.0.2 to the latest stable version (3.0.0).
Update to 3.0.0 yielded the following Exception - "**Tried to register two views with the same name RNCSafeAreaProvider**"
Stack trace got me to the line `import { Icon, Input } from 'react-native-elements'`
(Upgrading just to the previous version 2.3.3 was successful)

**Expected behavior (Required)**

Obviously, after such a major update I expected to be faced with plenty of errors. However, I expected to see more errors such as "no such import", "invalid props" allowing me to easier spot the error and adjust code.

**Describe the bug (Required)**

It seems that there is some unobvious imports collision causing this error or just some misleading error message.

**To Reproduce (Required)**

1. Configure a sample screen using react-navigation/stack -> "5.6.2" and react-native-elements -> "2.3.2"
2. On aforementioned screen use _Input_ and render _Icon_ as a leftIcon prop.
Example:
```
import { Icon, Input } from 'react-native-elements'
const SignInScreen = (props) => (
               <Input
                leftIcon={<Icon name={'mail'} />}
              />
)

```
4. Upgrade `react-native-elements` to version 3.0.0
5. You should be faced with Exception - "Tried to register two views with the same name RNCSafeAreaProvider"

**Screenshots (Required)**
![image](https://user-images.githubusercontent.com/15077823/102817119-74b14d00-43cf-11eb-838b-249f3bcbff5a.png)

**Your Environment (Required):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |3.0.0         |
| react-native          |    0.63.3     |

Thanks in advance for taking a look

**Comment by pranshuchittora** [comment]
Hi @pospieszynski can you try 
- Upgrading to RNE v3.0.1
- And run `expo install react-native-safe-area-context`
  run yarn or npm install

**Comment by pospieszynski** [comment]
Hi @pranshuchittora, thanks for responding. Unfortunately, the problem remains

**Comment by pranshuchittora** [comment]
I think that not related to RNE
https://github.com/th3rdwave/react-native-safe-area-context/issues/110#issuecomment-662580557

**Comment by flyingcircle** [comment]
I'm guessing that the issue is that you have 2 different versions of `react-native-safe-area-view` installed? Try seeing if that is the issue in your lock file.

**Comment by pospieszynski** [comment]
Yeah that was probably it. Not sure why this problem surfaced only after upgrading single package RNE though..Anyway, thanks for your comments. I am closing the issue.

**Comment by CKitisak** [comment]
Hi @pospieszynski , Would you please share how to solve the issue? 
Thanks

**Comment by bpolonia** [comment]
@CKitisak 

In `yarn.lock` I searched for `react-native-elements` and looked at its dependencies list to see what version of `react-native-safe-area-context` it depends on. 

In my case `react-native-elements` depends on `react-native-safe-area-context@3.1.9` but I also had `react-native-safe-area-context@3.1.4` installed. So I just deleted the 3.1.4 from my `yarn.lock`, `package.json` and `node_modules` and reinstalled it `@3.1.9`.

**Comment by grkemtneri** [comment]
same issue ı upgrade '3.0.0-alpha.' to '^3.1.0'. ı tried to remove node_modules then npm install but still not working 

    "react-native": "0.63.3",
    "react-native-safe-area-context": "^3.1.9",
    "react-native-elements": "^3.1.0",

**Comment by jdnichollsc** [comment]
why `react-native-safe-area-context` is not a peer dependency?

**Comment by sweetbrypie** [comment]
> @CKitisak
> 
> In `yarn.lock` I searched for `react-native-elements` and looked at its dependencies list to see what version of `react-native-safe-area-context` it depends on.
> 
> In my case `react-native-elements` depends on `react-native-safe-area-context@3.1.9` but I also had `react-native-safe-area-context@3.1.4` installed. So I just deleted the 3.1.4 from my `yarn.lock`, `package.json` and `node_modules` and reinstalled it `@3.1.9`.

Could you explain how you deleted the 3.1.4 version and reinstalled the 3.1.9 version? I am running into the same issue and am relatively new to navigating these kinds of errors, so I would appreciate the help! Thank you.

**Comment by walfly** [comment]
I think this should be reopened.   `react-native-safe-area-context` should be a peer dependency.  
<img width="396" alt="Screen Shot 2021-02-05 at 9 44 00 AM" src="https://user-images.githubusercontent.com/4022481/107069456-db7ba180-6796-11eb-8a3c-20dc663b85a5.png">

**Comment by shaolinmkz** [comment]
// Old package.json
```sh
react-navigation
@react-navigation/native
@react-navigation/stack
```

I had these three installed, I think it recognized `react-navigation` as a duplicate.
So I just uninstalled `react-navigation` and the error went away.

`yarn remove react-navigation`

// New package.json
```sh
@react-navigation/native
@react-navigation/stack
```

**Comment by ainvention** [comment]
I faced the same issue, but I solved with it
`npm install --legacy-peer-deps`

**Comment by MacKentoch** [comment]
**Why is this issue closed?**

Context: `NodeJS 16`

Still an issue with `"react-native-safe-area-context": "^4.0.1"` while trying to install `react-native-elements@v4.0.0-beta.0`.

**Comment by fukemy** [comment]
any solution here?

**Comment by NIshithshettyR** [comment]
Configuration: 
- expo@46.0.0
- react-native@0.69.6
- react-native-safe-area-context@4.3.1
- react-native-elements@3.4.2

```
While resolving: Native@1.0.0
npm WARN Found: react-native-safe-area-context@4.4.1
npm WARN node_modules/react-native-safe-area-context
npm WARN   peer react-native-safe-area-context@">= 3.0.0" from @react-navigation/elements@1.3.6
npm WARN   node_modules/@react-navigation/elements
npm WARN     @react-navigation/elements@"^1.3.6" from @react-navigation/native-stack@6.9.1
npm WARN     node_modules/@react-navigation/native-stack
npm WARN     1 more (@react-navigation/stack)
npm WARN   3 more (@react-navigation/native-stack, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react-native-safe-area-context@"^3.1.9" from react-native-elements@3.4.2
npm WARN node_modules/react-native-elements
npm WARN   react-native-elements@"^3.4.2" from the root project
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: rn-pdf-reader-js@4.1.1
npm ERR! Found: expo@46.0.17
npm ERR! node_modules/expo
npm ERR!   peer expo@"*" from expo-application@4.2.2
npm ERR!   node_modules/expo-application
npm ERR!     expo-application@"~4.2.2" from expo@46.0.17
npm ERR!     expo-application@"~4.2.0" from expo-notifications@0.16.1
npm ERR!     node_modules/expo-notifications
npm ERR!       expo-notifications@"^0.16.1" from the root project
npm ERR!   peer expo@"*" from expo-constants@14.0.2
npm ERR!   node_modules/expo-asset/node_modules/expo-constants
npm ERR!     expo-constants@"~14.0.0" from expo-asset@8.6.2
npm ERR!     node_modules/expo-asset
npm ERR!       expo-asset@"~8.6.1" from expo@46.0.17
npm ERR!       1 more (the root project)
npm ERR!   21 more (expo-file-system, expo-constants, expo-dev-client, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer expo@">= 33.0.x < 37.0.x" from rn-pdf-reader-js@4.1.1
npm ERR! node_modules/rn-pdf-reader-js
npm ERR!   rn-pdf-reader-js@"^4.1.1" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: expo@36.0.2
npm ERR! node_modules/expo
npm ERR!   peer expo@">= 33.0.x < 37.0.x" from rn-pdf-reader-js@4.1.1
npm ERR!   node_modules/rn-pdf-reader-js
npm ERR!     rn-pdf-reader-js@"^4.1.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps

```
What should I do to resolve this issue? Any suggestions

**Comment by fukemy** [comment]
***Fix the upstream dependency conflict, or retry this command with --force, or --legacy-peer-deps***
