### ISSUE TITLE
Search bar ts error

### ISSUE THREAD

**Issue by aliwaqar9811** [react-native-elements/react-native-elements#3163]
**Explain what you did (Required)**

I'm trying to use SearchBar Component from react-native-elements

**Expected behavior (Required)**

It shouldn't give typescript error when I provide all necessary props

**Describe the bug (Required)**

It's showing error that some necessary props are missing even I give all props;

**To Reproduce (Required)**

1- Initialize a project having typescript.
2- Install react-native-elements 3.4.2 in your project.
3- Try to use SearchBar component from it.
4- See typescript errors

**Screenshots (Required)**

<img width="910" alt="Screen Shot 2021-08-04 at 8 06 43 PM" src="https://user-images.githubusercontent.com/88022655/128206671-4ebb162a-3d91-4e8f-b13e-cc8c4ac674f2.png">
<img width="910" alt="Screen Shot 2021-08-04 at 8 07 07 PM" src="https://user-images.githubusercontent.com/88022655/128206720-ff415032-0f90-4c07-b1ee-65ffa7dec21c.png">

**Your Environment (Required):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |     3.4.2    |
| react-native          |      0.64.2   |

**Comment by ilsong** [comment]
![image](https://user-images.githubusercontent.com/20615642/128887820-e6c21f38-573c-4214-99ef-a1e1d1b2d9e8.png)
same issue

**Comment by arpitBhalla** [comment]
fixed by #3099

**Comment by ilsong** [comment]
```
import { SearchBar, Button } from 'react-native-elements';

const Section: React.FC = () => {
  return (
    <View style={styles.sectionContainer}>
      <Button title="solid button"/>
      <SearchBar></SearchBar> // error
    </View>
  );
};
```

software | version
-- | --
react-native-elements | 3.4.2
react-native | 0.64.1

Still have issue @arpitBhalla. Could you help?

**Comment by anthowm** [comment]
@ilsong if you have a hook and can't wait for next release just patch the package.
go to node_modules/react-native-elements/searchbar/SearchBar.d.ts and change like this

```
export declare type SearchBarProps = SearchBarBaseProps | SearchBarDefaultProps | SearchBarAndroidProps | SearchBarIosProps;

// and this line change Pick for Partial and change all & to |
declare const _default: React.FunctionComponent<Partial<import("react-native").TextInputProps | React.RefAttributes<TextInput> 
```
then npx patch-package react-native-elements

**Comment by Rahul1d** [comment]
> @ilsong if you have a hook and can't wait for next release just patch the package.
> go to node_modules/react-native-elements/searchbar/SearchBar.d.ts and change like this
> 
> ```
> export declare type SearchBarProps = SearchBarBaseProps | SearchBarDefaultProps | SearchBarAndroidProps | SearchBarIosProps;
> 
> // and this line change Pick for Partial and change all & to |
> declare const _default: React.FunctionComponent<Partial<import("react-native").TextInputProps | React.RefAttributes<TextInput> 
> ```
> 
> then npx patch-package react-native-elements

Hi @anthowm , I tried this Partial change, but doest work. Also i am getting some argument errors. 
![image](https://user-images.githubusercontent.com/19947716/132122339-c03d32ca-09a7-41b4-98cb-3be435cd2fc0.png)

**Comment by christopher-caldwell** [comment]
@trajano Got this error with your hack. What a mess this is. Just going to ts-ignore this error.

![Screen Shot 2021-12-02 at 3 54 53 PM](https://user-images.githubusercontent.com/62559469/144516087-ec066537-2dfa-4b5c-8eed-51447ad133f2.png)

**Comment by trajano** [comment]
@christopher-caldwell did you make sure you have the same imports as I have? I am also on    "react-native-elements": "^3.4.2",

**Comment by christopher-caldwell** [comment]
@trajano Yep. Copied your code exactly. Same version as well.

**Comment by trajano** [comment]
This is the one that I copied from my code base.

```
import React from 'react';
import { SearchBar as RNESearchBar, SearchBarProps } from 'react-native-elements';
/**
 * This "hacks" the react-native-elements Search Bar due to a bad typing job
 * https://github.com/react-native-elements/react-native-elements/issues/3163
 */
export function SearchBar(
  props: Partial<Omit<SearchBarProps, 'searchIcon' | 'onChangeText'>> & {
    onChangeText?(text: string): void;
    searchIcon?: () => JSX.Element;
  }
) {
  return <RNESearchBar {...(props as unknown as SearchBarProps)} />;
}
```

**Comment by christopher-caldwell** [comment]
@trajano I copied this exactly, restarted the TS server and got the same error. I've already fixed this for my own use, just letting you know this didn't work for me.

## Code screenshot
![Screen Shot 2021-12-03 at 2 43 17 PM](https://user-images.githubusercontent.com/62559469/144676685-7732ae43-cd35-4686-890b-0dcf0f227257.png)

## Error Screenshot
![Screen Shot 2021-12-03 at 2 43 28 PM](https://user-images.githubusercontent.com/62559469/144676679-159fd1c8-0dc3-43ea-a038-dd054e176306.png)

**Comment by arpitBhalla** [comment]
Can you test with v4.0.0-beta

**Comment by monk-lee** [comment]
> Can you test with v4.0.0-beta

4.0.0-rc.0

same issue
