### ISSUE TITLE
Tab indicator randomly not displayed on first render

### ISSUE THREAD

**Issue by marcoturi** [react-native-elements/react-native-elements#3407]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Explain what you did

I'm using Tab and Tab view. Navigating in a view using the components.

### Expected behavior

Indicator should be present from start.

### Describe the bug

When the view (modal or component) opens, randomly, no indicator of the active tab is present. 

### Steps To Reproduce

```markdown
Open the component with Tab and TabView.
```

### Screenshots
https://user-images.githubusercontent.com/314901/159169896-8a223e24-6b95-4b60-afb9-37c8cd76a33b.mp4

### Your Environment

```markdown
    "react-native": "0.66.0",
    "@react-native-elements/base": "^4.0.0-rc.0",
    "@react-native-elements/themed": "^4.0.0-rc.0",
```

**Comment by marcoturi** [comment]
Update: I found same interesting thing:
- The bug is random
- Disabling swipe doesn't affect the bug
- The bug is present in both modal and normal screens.
- It can be temporary fixed by giving a fixed width in the indicator style:

```
            indicatorStyle={{
              backgroundColor: appColors.text,
              height: 3,
              width: '33%',
            }}
```

**Comment by marcoturi** [comment]
Just an hint for the maintainers, there is a race condition in the component:
https://github.com/react-native-elements/react-native-elements/blob/next/packages/base/src/Tab/Tab.tsx#L129

If you put a console log on L129 and L164 you will see (randomly):

 LOG  L129 WIDTH undefined
 LOG   L164 WIDTH  120
 LOG   L164 WIDTH  120
 LOG   L164 WIDTH  120

The width used for the indicator (ie const WIDTH = tabItemsPosition.current[value]?.width;) is defined before is calculated.

**Comment by arpitBhalla** [comment]
Would you like to create a PR to fix this?

**Comment by arpitBhalla** [comment]
AFA I can remember, it's because it don't rerender after calculating container width, because I didn't added state, instead I was using ref, so changing it might fix this.

**Comment by marcoturi** [comment]
@arpitBhalla I have found another related bug. Sometime the indicator is shown only on the first 2 tab. When you click on the 3rd tab the indicator stay on the last one selected (but the tab content is correctly displayed).

**Comment by arpitBhalla** [comment]
Can you share code so I can repro this issue?

**Comment by marcoturi** [comment]
4.0.0rc1 didn't fix any issue. It also adds problems with slides overlapping each other.
To repro just open the component view in a modal or new page.

![simulator_screenshot_7AFC22BE-8ACF-4312-B87E-5B01C0CD301A](https://user-images.githubusercontent.com/314901/162617423-942937c1-6bc2-4c2a-bf6f-91f630196026.png)

**Comment by arpitBhalla** [comment]
Hey, can you share snack for this, if possible?

> 4.0.0rc1 didn't fix any issue

I released it because there was some issue with installation via GitHub registry.

**Comment by davide-acanfora** [comment]
Hello, the problem is still present in version 4.0.0-rc.7 on iOS only.

> Update: I found same interesting thing:
> 
> * The bug is random
> * Disabling swipe doesn't affect the bug
> * The bug is present in both modal and normal screens.
> * It can be temporary fixed by giving a fixed width in the indicator style:
> 
> ```
>             indicatorStyle={{
>               backgroundColor: appColors.text,
>               height: 3,
>               width: '33%',
>             }}
> ```
This temporary fix seems to work instead.

You can reproduce the error by simply running the snack [in the documentation](https://reactnativeelements.com/docs/components/tab#active-tab-items). Try to open and close the snack few times on iOS and you will notice the issue appear randomly, sooner or later

**Comment by giotiskl** [comment]
Yes, error is still reproducible. The temp fix works.

**Comment by Praveer-grover** [comment]
I was trying to debug this issue and this is what I found. On IOS, the tabItemPositions are calculated out of order

**Comment by Praveer-grover** [comment]
I was trying to debug this issue and found that on ios, the onLayout function (below):
![image](https://user-images.githubusercontent.com/5112582/211216512-8961b381-6d83-48f5-9fdb-f0230d365f25.png)

  is called out of order 
  
![image](https://user-images.githubusercontent.com/5112582/211216354-a30a2459-d10d-482b-99ed-c3cd99126293.png)
Hence, the tabItemPositions are calculated incorrectly which causes the issue where the indicator position is incorrect. Would need some advise on how to fix this?
I was thinking to create a ref which would just hold the index and width, then when all children's onLayout have finished. Then we can calculate tabItemPositions. Is there such handler on ScrollView? Or any other ideas on how to fix this?

**Comment by derochedesign** [comment]
Just adding my experience: first tab is often not highlighted, but also the final tab will never display the indicator, even though it does switch to the tab (and highlights the tab text). iOS only; android works fine. the temp fix above does not fix this for me.
https://user-images.githubusercontent.com/38788426/215333409-58a77491-ccf2-4db5-95b1-35b9bc36649e.mov

**Comment by derochedesign** [comment]
> Just adding my experience: first tab is often not highlighted, but also the final tab will never display the indicator, even though it does switch to the tab (and highlights the tab text). iOS only; android works fine. the temp fix above does not fix this for me. https://user-images.githubusercontent.com/38788426/215333409-58a77491-ccf2-4db5-95b1-35b9bc36649e.mov

I managed to temporary fix the final tab not getting the indicator by adding a fourth `Tab.Item` and giving it a style of `display: none`. Interestingly, it seems like both two and four tabs does not have the same issue; only 3.

**Comment by PoojaBabusingh** [comment]
> @arpitBhalla I have found another related bug. Sometime the indicator is shown only on the first 2 tab. When you click on the 3rd tab the indicator stay on the last one selected (but the tab content is correctly displayed).

Hey is there an issue created for this? I have the fix.

**Comment by DarylBeattie** [comment]
FYI this seems to only happen to me when the Tabs are contained in a View that is not 100% width. They also happen to be in a container that is flex-direction: row (because I have something _beside_ my Tabs).

**Comment by MickaelAustoni** [comment]
Hello, the problem is still present on iOS only  (version 4.0.0-rc.8)

**Comment by KristianLentino99** [comment]
The problem is still here also on Android, the workaround worked

**Comment by juanortiz10** [comment]
The workaround does not work if you use `scrollable` property in the `Tab` component

**Comment by 1night2zero** [comment]
```tsx
  React.useEffect(() => {
    if (index === 0) {
      handleTabChange(0);
    }
  }, []);
```
  Change tab index value on first time render, can be a temporary solution for me.

**Comment by theianmay** [comment]
@deepktp 's recent PRs should have resolved this. Closing - if there are any new considerations, please open a new issue and we will add it to the upcoming roadmap.
